name: setes_mobile
description: Sports Community.

publish_to: "none"

version: 1.0.1+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.9
  http: ^0.13.4
  cupertino_icons: ^1.0.2
  flutter_datetime_picker: ^1.5.1
  razorpay_flutter: ^1.2.7
  webview_flutter: ^3.0.0
  image_picker: ^0.8.4+8
  geolocator: ^8.2.0
  screenshot: ^1.2.3
  flutter_share: ^2.0.0
  url_launcher: ^6.0.20
  path_provider: ^2.0.9
  clipboard: ^0.1.3
  web_socket_channel: ^2.1.0
  flutter_local_notifications: ^9.4.0
  mac_address: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/loginBg.jpeg
    - assets/playerBg.png
    - assets/scoreBordBg.png
    - assets/bg_a.png
    - assets/bg_team.png
    - assets/social.png
    - assets/Group 68.png
    - assets/Path 30.png
    - assets/setes_booking.png
    - assets/events.png
    
    - assets/setes.jpeg
    - assets/setes.png

    - assets/leader_bord.png
    - assets/Group 67.png
    - assets/Group 60.png
    - assets/Group 47.png
    - assets/pro_bg.png

    - assets/setes_loading.png

    - assets/icon/user_lock.png